"""PDF report generation module.

Generates a professional wind load calculation report with:
- Project metadata header
- Input parameters
- ASCE 7-22 calculation breakdown
- Line and terminal post results
- Structural status and risk assessment
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from windcalc.schemas import EstimateInput, EstimateOutput


def generate_pdf_report(data: dict[str, Any], output_path: str) -> None:
    """Legacy wrapper kept for backward compatibility."""
    path = Path(output_path)
    draw_pdf(path, None, None, extra=data)


def draw_pdf(
    output_path: Path,
    input_data: EstimateInput | None,
    result: EstimateOutput | None,
    extra: dict[str, Any] | None = None,
    risk_status: str | None = None,
    risk_details: dict[str, Any] | None = None,
    project_meta: dict[str, str] | None = None,
) -> None:
    """Generate a PDF report for wind load calculation results."""
    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=letter,
        topMargin=0.6 * inch,
        bottomMargin=0.6 * inch,
    )
    styles = getSampleStyleSheet()
    story = []

    # ── Title & Project Metadata ─────────────────────────────────────
    title = Paragraph("Wind Load Calculation Report", styles["Title"])
    story.append(title)

    subtitle_parts = []
    if project_meta:
        if project_meta.get("project_name"):
            subtitle_parts.append(f"<b>Project:</b> {project_meta['project_name']}")
        if project_meta.get("location"):
            subtitle_parts.append(f"<b>Location:</b> {project_meta['location']}")
        if project_meta.get("estimator"):
            subtitle_parts.append(f"<b>Estimator:</b> {project_meta['estimator']}")
    subtitle_parts.append(
        f"<b>Date:</b> {datetime.now().strftime('%B %d, %Y at %I:%M %p')}"
    )
    for part in subtitle_parts:
        story.append(Paragraph(part, styles["Normal"]))
    story.append(Spacer(1, 0.25 * inch))

    # ── Input Section ────────────────────────────────────────────────
    if input_data:
        story.extend(_input_section(input_data, styles))

    # ── ASCE 7 Breakdown ─────────────────────────────────────────────
    if result and result.shared.design_params:
        story.extend(_asce7_section(input_data, result, styles))

    # ── Results Section ──────────────────────────────────────────────
    if result:
        story.extend(_result_section(result, styles))

    # ── Status Section ───────────────────────────────────────────────
    if risk_status and risk_details:
        story.extend(_status_section(risk_status, risk_details, styles))

    # ── Legacy Section ───────────────────────────────────────────────
    if extra:
        story.extend(_legacy_section(extra, styles))

    # ── Footer Disclaimer ────────────────────────────────────────────
    story.append(Spacer(1, 0.3 * inch))
    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=7,
        textColor=colors.grey,
        leading=9,
    )
    story.append(Paragraph(
        "This report is generated by the HFC Wind Load Calculator for "
        "estimation purposes only. It does not replace a licensed "
        "Professional Engineer's sealed calculations. Verify all values "
        "against project drawings and local building code requirements.",
        disclaimer_style,
    ))

    doc.build(story)


def _input_section(
    data: EstimateInput,
    styles: dict[str, ParagraphStyle],
) -> list:
    story: list = []
    story.append(Paragraph("<b>Input Parameters</b>", styles["Heading2"]))

    rows = [
        ["Wind Speed", f"{data.wind_speed_mph} mph"],
        ["Exposure Category", data.exposure],
        ["Risk Category", data.risk_category],
        ["Fence Height", f"{data.height_total_ft} ft"],
        ["Post Spacing", f"{data.post_spacing_ft} ft"],
        ["Bay Area", f"{data.area_per_bay_ft2:.1f} sq ft"],
    ]
    if data.fence_length_ft:
        bs = data.aspect_ratio_bs
        bs_str = f" (B/s = {bs:.1f})" if bs else ""
        rows.append(["Fence Run Length", f"{data.fence_length_ft:.0f} ft{bs_str}"])
    if data.fence_type:
        rows.append(["Fence Type", data.fence_type.replace("_", " ").title()])
    if data.soil_type and data.soil_type != "default":
        rows.append(["Soil Type", data.soil_type])

    table = Table(rows, colWidths=[2.5 * inch, 4.0 * inch])
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.Color(0.93, 0.93, 0.93)),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(table)
    story.append(Spacer(1, 0.2 * inch))
    return story


def _asce7_section(
    input_data: EstimateInput | None,
    result: EstimateOutput,
    styles: dict[str, ParagraphStyle],
) -> list:
    """ASCE 7-22 intermediate calculation breakdown."""
    story: list = []
    dp = result.shared.design_params
    if not dp:
        return story

    story.append(Paragraph("<b>ASCE 7-22 Calculation Breakdown</b>", styles["Heading2"]))

    mono = ParagraphStyle("Mono", parent=styles["Normal"], fontName="Courier", fontSize=9)

    ws = input_data.wind_speed_mph if input_data else "V"
    story.append(Paragraph(
        f"qz = 0.00256 x Kz x Kzt x Kd x V^2 = "
        f"0.00256 x {dp.kz:.3f} x {dp.kzt} x {dp.kd} x {ws}^2 = "
        f"<b>{dp.qz_psf:.2f} psf</b>",
        mono,
    ))
    story.append(Paragraph(
        f"p  = qz x G x Cf = {dp.qz_psf:.2f} x {dp.g} x {dp.cf:.3f} = "
        f"<b>{result.shared.pressure_psf:.2f} psf</b>",
        mono,
    ))
    story.append(Spacer(1, 0.1 * inch))

    rows = [
        ["Parameter", "Value", "Reference"],
        ["Kz (exposure coeff.)", f"{dp.kz:.4f}", "Table 26.10-1"],
        ["Kzt (topographic)", f"{dp.kzt}", "Section 26.8"],
        ["Kd (directionality)", f"{dp.kd}", "Table 26.6-1"],
        ["G (gust-effect)", f"{dp.g}", "Section 26.11"],
        ["Cf,solid", f"{dp.cf_solid:.3f}", "Figure 29.3-1"],
        ["Solidity (epsilon)", f"{dp.solidity:.2f}", "Fence type"],
        ["Cf (net)", f"{dp.cf:.3f}", "Cf,solid x epsilon"],
        ["qz", f"{dp.qz_psf:.2f} psf", "Eq. 26.10-1"],
    ]

    table = Table(rows, colWidths=[2.0 * inch, 1.5 * inch, 2.5 * inch])
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.Color(0.15, 0.25, 0.45)),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 8),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("BACKGROUND", (0, 1), (-1, -1), colors.Color(0.97, 0.97, 0.97)),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ])
    )
    story.append(table)
    story.append(Spacer(1, 0.2 * inch))
    return story


def _recommendation_cell(result: EstimateOutput) -> str:
    rec = result.recommended
    post = rec.post_label or rec.post_key or rec.post_size or "N/A"
    dia = rec.footing_diameter_in or "N/A"
    emb = rec.embedment_in or "N/A"
    return f"{post} footing {dia} in dia x {emb} in"


def _result_section(
    result: EstimateOutput,
    styles: dict[str, ParagraphStyle],
) -> list:
    story: list = []
    story.append(Paragraph("<b>Results Summary</b>", styles["Heading2"]))

    rows = [
        ["Design Pressure", f"{result.pressure_psf:.2f} psf"],
        ["Total Bay Load", f"{result.total_load_lb:.0f} lb"],
        ["Load Per Post", f"{result.load_per_post_lb:.0f} lb"],
    ]

    # Line post
    line = result.line
    rows.append(["Line Post", line.recommended.post_label or "Auto"])
    if line.max_spacing_ft:
        rows.append(["  Max Spacing (Line)", f"{line.max_spacing_ft:.2f} ft"])
    if line.spacing_ratio is not None:
        rows.append(["  Spacing Utilization", f"{line.spacing_ratio * 100:.0f}%"])
    if line.moment_ratio is not None:
        rows.append(["  Bending Utilization", f"{line.moment_ratio * 100:.0f}% (advisory)"])

    # Terminal post
    term = result.terminal
    rows.append(["Terminal Post", term.recommended.post_label or "Auto"])
    if term.max_spacing_ft:
        rows.append(["  Max Spacing (Terminal)", f"{term.max_spacing_ft:.2f} ft"])
    if term.moment_ratio is not None:
        rows.append(["  Bending Utilization", f"{term.moment_ratio * 100:.0f}%"])

    table = Table(rows, colWidths=[2.5 * inch, 4.0 * inch])
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.Color(0.93, 0.93, 0.93)),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    story.append(table)
    story.append(Spacer(1, 0.2 * inch))

    if result.warnings:
        story.append(Paragraph("<b>Warnings</b>", styles["Heading3"]))
        for warning in result.warnings:
            story.append(Paragraph(f"- {warning}", styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    if result.assumptions:
        story.append(Paragraph("<b>Assumptions</b>", styles["Heading3"]))
        for assumption in result.assumptions:
            story.append(Paragraph(f"- {assumption}", styles["Normal"]))

    return story


def _legacy_section(
    data: dict[str, Any],
    styles: dict[str, ParagraphStyle],
) -> list:
    story: list = []
    story.append(Paragraph("<b>Legacy Summary</b>", styles["Heading2"]))

    fence_specs = data.get("fence_specs", {})
    wind_cond = data.get("wind_conditions", {})
    results_data = [
        ["Design Pressure", f"{data.get('design_pressure', 'N/A')} psf"],
        ["Total Load", f"{data.get('total_load', 'N/A')} lbs"],
    ]
    fence_data = [
        ["Height", f"{fence_specs.get('height', 'N/A')} ft"],
        ["Width", f"{fence_specs.get('width', 'N/A')} ft"],
        ["Material", fence_specs.get("material", "N/A")],
        ["Location", fence_specs.get("location", "N/A")],
    ]
    wind_data = [
        ["Wind Speed", f"{wind_cond.get('wind_speed', 'N/A')} mph"],
        ["Exposure Category", wind_cond.get("exposure_category", "N/A")],
        ["Importance Factor", wind_cond.get("importance_factor", "N/A")],
    ]

    for title, rows in (
        ("Fence Specifications", fence_data),
        ("Wind Conditions", wind_data),
        ("Calculation Results", results_data),
    ):
        story.append(Paragraph(f"<b>{title}</b>", styles["Heading3"]))
        table = Table(rows)
        table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
            ])
        )
        story.append(table)
        story.append(Spacer(1, 0.1 * inch))

    if data.get("calculation_notes"):
        story.append(
            Paragraph(f"<b>Notes:</b> {data['calculation_notes']}", styles["Normal"])
        )

    return story


def _status_section(
    risk_status: str,
    risk_details: dict[str, Any],
    styles: dict[str, ParagraphStyle],
) -> list:
    """Add structural status section to PDF."""
    story: list = []
    story.append(Paragraph("<b>Structural Status</b>", styles["Heading2"]))

    if risk_status == "GREEN":
        status_text = "GREEN - Configuration is within recommended limits"
        status_footer = "Meets preliminary structural criteria."
        bg_color = colors.Color(0.85, 0.95, 0.85)
        text_color = colors.Color(0.0, 0.4, 0.0)
    elif risk_status == "YELLOW":
        status_text = "YELLOW - Configuration is near a structural limit (85-100%)"
        status_footer = "Near-limit preliminary result - review recommended."
        bg_color = colors.Color(1.0, 0.97, 0.80)
        text_color = colors.Color(0.6, 0.4, 0.0)
    else:
        status_text = "RED - Configuration exceeds structural limits"
        status_footer = "NOT acceptable - change post size, spacing, or seek engineering."
        bg_color = colors.Color(1.0, 0.85, 0.85)
        text_color = colors.Color(0.6, 0.0, 0.0)

    status_style = ParagraphStyle(
        "StatusHeader",
        parent=styles["Normal"],
        fontSize=11,
        textColor=text_color,
        backColor=bg_color,
        borderPadding=8,
        borderWidth=1,
        borderColor=text_color,
    )
    story.append(Paragraph(f"<b>{status_text}</b>", status_style))
    story.append(Spacer(1, 0.15 * inch))

    if risk_details.get("reasons"):
        story.append(Paragraph("<b>Status Details:</b>", styles["Heading3"]))
        for reason in risk_details["reasons"]:
            story.append(Paragraph(f"- {reason}", styles["Normal"]))
        story.append(Spacer(1, 0.1 * inch))

    ratio_rows = []
    if risk_details.get("line_spacing_ratio") is not None:
        ratio_rows.append([
            "Line Spacing Utilization",
            f"{risk_details['line_spacing_ratio'] * 100:.1f}%",
        ])
    if risk_details.get("terminal_bending_ratio") is not None:
        ratio_rows.append([
            "Terminal Bending Utilization",
            f"{risk_details['terminal_bending_ratio'] * 100:.1f}%",
        ])

    if ratio_rows:
        ratio_table = Table(ratio_rows, colWidths=[3.0 * inch, 2.0 * inch])
        ratio_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), colors.lightgrey),
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
            ])
        )
        story.append(ratio_table)
        story.append(Spacer(1, 0.1 * inch))

    footer_style = ParagraphStyle(
        "StatusFooter",
        parent=styles["Normal"],
        fontSize=9,
        textColor=text_color,
    )
    story.append(Paragraph(f"<i>{status_footer}</i>", footer_style))
    story.append(Spacer(1, 0.2 * inch))

    return story


__all__ = ["draw_pdf", "generate_pdf_report"]
